package com.xstudio.discuzx.ultrax.mapper;

import com.xstudio.discuzx.ultrax.model.ForumForumfield;
import com.xstudio.spring.mybatis.pagehelper.IMybatisPageHelperDao;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface ForumForumfieldMapper extends IMybatisPageHelperDao<ForumForumfield, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_forum_forumfield
     *
     * @mbg.generated
     */
    @Override
    List<ForumForumfield> selectByExampleWithBLOBs(@Param("example") ForumForumfield record, @Param("pageBounds") RowBounds pageBounds);
}