package com.xstudio.discuzx.ultrax.model;

import com.xstudio.tool.utils.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Database Table Remarks:
 *   会员用户组权限表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_usergroup_field
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonUsergroupField extends BaseModelObject<Short> implements Serializable {
    /**
     * Database Column Remarks:
     *   会员组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.groupid
     *
     * @mbg.generated
     */
    private Short groupid;

    /**
     * Database Column Remarks:
     *   阅读权限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.readaccess
     *
     * @mbg.generated
     */
    private Byte readaccess;

    /**
     * Database Column Remarks:
     *   允许发帖
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpost
     *
     * @mbg.generated
     */
    private Boolean allowpost;

    /**
     * Database Column Remarks:
     *   允许回复
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowreply
     *
     * @mbg.generated
     */
    private Boolean allowreply;

    /**
     * Database Column Remarks:
     *   允许发表投票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostpoll
     *
     * @mbg.generated
     */
    private Boolean allowpostpoll;

    /**
     * Database Column Remarks:
     *   允许发表悬赏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostreward
     *
     * @mbg.generated
     */
    private Boolean allowpostreward;

    /**
     * Database Column Remarks:
     *   允许发表交易
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowposttrade
     *
     * @mbg.generated
     */
    private Boolean allowposttrade;

    /**
     * Database Column Remarks:
     *   允许发表活动
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostactivity
     *
     * @mbg.generated
     */
    private Boolean allowpostactivity;

    /**
     * Database Column Remarks:
     *   是否需要审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowdirectpost
     *
     * @mbg.generated
     */
    private Boolean allowdirectpost;

    /**
     * Database Column Remarks:
     *   允许下载附件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowgetattach
     *
     * @mbg.generated
     */
    private Boolean allowgetattach;

    /**
     * Database Column Remarks:
     *   允许查看图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowgetimage
     *
     * @mbg.generated
     */
    private Boolean allowgetimage;

    /**
     * Database Column Remarks:
     *   允许上传附件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostattach
     *
     * @mbg.generated
     */
    private Boolean allowpostattach;

    /**
     * Database Column Remarks:
     *   允许上传图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostimage
     *
     * @mbg.generated
     */
    private Boolean allowpostimage;

    /**
     * Database Column Remarks:
     *   允许参与投票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowvote
     *
     * @mbg.generated
     */
    private Boolean allowvote;

    /**
     * Database Column Remarks:
     *   允许搜索
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsearch
     *
     * @mbg.generated
     */
    private Boolean allowsearch;

    /**
     * Database Column Remarks:
     *   允许自定义头衔
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcstatus
     *
     * @mbg.generated
     */
    private Boolean allowcstatus;

    /**
     * Database Column Remarks:
     *   允许隐身登录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowinvisible
     *
     * @mbg.generated
     */
    private Boolean allowinvisible;

    /**
     * Database Column Remarks:
     *   允许积分转帐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowtransfer
     *
     * @mbg.generated
     */
    private Boolean allowtransfer;

    /**
     * Database Column Remarks:
     *   允许设置阅读权限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsetreadperm
     *
     * @mbg.generated
     */
    private Boolean allowsetreadperm;

    /**
     * Database Column Remarks:
     *   允许设置附件权限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsetattachperm
     *
     * @mbg.generated
     */
    private Boolean allowsetattachperm;

    /**
     * Database Column Remarks:
     *   允许使用标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowposttag
     *
     * @mbg.generated
     */
    private Boolean allowposttag;

    /**
     * Database Column Remarks:
     *   允许使用hide代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowhidecode
     *
     * @mbg.generated
     */
    private Boolean allowhidecode;

    /**
     * Database Column Remarks:
     *   允许使用html
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowhtml
     *
     * @mbg.generated
     */
    private Boolean allowhtml;

    /**
     * Database Column Remarks:
     *   允许匿名发帖
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowanonymous
     *
     * @mbg.generated
     */
    private Boolean allowanonymous;

    /**
     * Database Column Remarks:
     *   允许签名使用bbcode
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsigbbcode
     *
     * @mbg.generated
     */
    private Boolean allowsigbbcode;

    /**
     * Database Column Remarks:
     *   允许使用img
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsigimgcode
     *
     * @mbg.generated
     */
    private Boolean allowsigimgcode;

    /**
     * Database Column Remarks:
     *   允许使用道具
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowmagics
     *
     * @mbg.generated
     */
    private Boolean allowmagics;

    /**
     * Database Column Remarks:
     *   不受时间段限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.disableperiodctrl
     *
     * @mbg.generated
     */
    private Boolean disableperiodctrl;

    /**
     * Database Column Remarks:
     *   操作理由短信通知作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.reasonpm
     *
     * @mbg.generated
     */
    private Boolean reasonpm;

    /**
     * Database Column Remarks:
     *   主题最大售价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxprice
     *
     * @mbg.generated
     */
    private Short maxprice;

    /**
     * Database Column Remarks:
     *   最大签名尺寸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxsigsize
     *
     * @mbg.generated
     */
    private Short maxsigsize;

    /**
     * Database Column Remarks:
     *   最大附件尺寸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxattachsize
     *
     * @mbg.generated
     */
    private Integer maxattachsize;

    /**
     * Database Column Remarks:
     *   每天最大附件总尺寸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxsizeperday
     *
     * @mbg.generated
     */
    private Integer maxsizeperday;

    /**
     * Database Column Remarks:
     *   每小时发主题数限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxthreadsperhour
     *
     * @mbg.generated
     */
    private Byte maxthreadsperhour;

    /**
     * Database Column Remarks:
     *   每小时发回帖数限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxpostsperhour
     *
     * @mbg.generated
     */
    private Byte maxpostsperhour;

    /**
     * Database Column Remarks:
     *   允许发表的附件类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.attachextensions
     *
     * @mbg.generated
     */
    private String attachextensions;

    /**
     * Database Column Remarks:
     *   评分范围
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.raterange
     *
     * @mbg.generated
     */
    private String raterange;

    /**
     * Database Column Remarks:
     *   每日打卡奖励
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.loginreward
     *
     * @mbg.generated
     */
    private String loginreward;

    /**
     * Database Column Remarks:
     *   交易最小积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.mintradeprice
     *
     * @mbg.generated
     */
    private Short mintradeprice;

    /**
     * Database Column Remarks:
     *   交易最大积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxtradeprice
     *
     * @mbg.generated
     */
    private Short maxtradeprice;

    /**
     * Database Column Remarks:
     *   悬赏最小积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.minrewardprice
     *
     * @mbg.generated
     */
    private Short minrewardprice;

    /**
     * Database Column Remarks:
     *   悬赏最大积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxrewardprice
     *
     * @mbg.generated
     */
    private Short maxrewardprice;

    /**
     * Database Column Remarks:
     *   道具折扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.magicsdiscount
     *
     * @mbg.generated
     */
    private Boolean magicsdiscount;

    /**
     * Database Column Remarks:
     *   道具负载最大值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxmagicsweight
     *
     * @mbg.generated
     */
    private Short maxmagicsweight;

    /**
     * Database Column Remarks:
     *   允许发表辩论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostdebate
     *
     * @mbg.generated
     */
    private Boolean allowpostdebate;

    /**
     * Database Column Remarks:
     *   可商品推荐数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.tradestick
     *
     * @mbg.generated
     */
    private Boolean tradestick;

    /**
     * Database Column Remarks:
     *   用户组表达式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.exempt
     *
     * @mbg.generated
     */
    private Boolean exempt;

    /**
     * Database Column Remarks:
     *   最大每天附件数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxattachnum
     *
     * @mbg.generated
     */
    private Short maxattachnum;

    /**
     * Database Column Remarks:
     *   是否允许发送含 url 内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowposturl
     *
     * @mbg.generated
     */
    private Boolean allowposturl;

    /**
     * Database Column Remarks:
     *   是否允许评价主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowrecommend
     *
     * @mbg.generated
     */
    private Boolean allowrecommend;

    /**
     * Database Column Remarks:
     *   允许发表抢楼帖
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostrushreply
     *
     * @mbg.generated
     */
    private Boolean allowpostrushreply;

    /**
     * Database Column Remarks:
     *   最多好友数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxfriendnum
     *
     * @mbg.generated
     */
    private Short maxfriendnum;

    /**
     * Database Column Remarks:
     *   空间大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maxspacesize
     *
     * @mbg.generated
     */
    private Integer maxspacesize;

    /**
     * Database Column Remarks:
     *   发表留言/评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcomment
     *
     * @mbg.generated
     */
    private Boolean allowcomment;

    /**
     * Database Column Remarks:
     *   发表文章的评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcommentarticle
     *
     * @mbg.generated
     */
    private Short allowcommentarticle;

    /**
     * Database Column Remarks:
     *   两次搜索操作间隔
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.searchinterval
     *
     * @mbg.generated
     */
    private Short searchinterval;

    /**
     * Database Column Remarks:
     *   是否免费搜索
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.searchignore
     *
     * @mbg.generated
     */
    private Boolean searchignore;

    /**
     * Database Column Remarks:
     *   发表日志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowblog
     *
     * @mbg.generated
     */
    private Boolean allowblog;

    /**
     * Database Column Remarks:
     *   发表记录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowdoing
     *
     * @mbg.generated
     */
    private Boolean allowdoing;

    /**
     * Database Column Remarks:
     *   上传图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowupload
     *
     * @mbg.generated
     */
    private Boolean allowupload;

    /**
     * Database Column Remarks:
     *   发布分享
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowshare
     *
     * @mbg.generated
     */
    private Boolean allowshare;

    /**
     * Database Column Remarks:
     *   发表日志需要审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowblogmod
     *
     * @mbg.generated
     */
    private Boolean allowblogmod;

    /**
     * Database Column Remarks:
     *   发表记录需要审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowdoingmod
     *
     * @mbg.generated
     */
    private Boolean allowdoingmod;

    /**
     * Database Column Remarks:
     *   上传图片需要审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowuploadmod
     *
     * @mbg.generated
     */
    private Boolean allowuploadmod;

    /**
     * Database Column Remarks:
     *   发布分享需要审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsharemod
     *
     * @mbg.generated
     */
    private Boolean allowsharemod;

    /**
     * Database Column Remarks:
     *   允许自定义CSS
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcss
     *
     * @mbg.generated
     */
    private Boolean allowcss;

    /**
     * Database Column Remarks:
     *   允许打招呼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpoke
     *
     * @mbg.generated
     */
    private Boolean allowpoke;

    /**
     * Database Column Remarks:
     *   允许加好友
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowfriend
     *
     * @mbg.generated
     */
    private Boolean allowfriend;

    /**
     * Database Column Remarks:
     *   允许表态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowclick
     *
     * @mbg.generated
     */
    private Boolean allowclick;

    /**
     * Database Column Remarks:
     *   允许使用道具
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowmagic
     *
     * @mbg.generated
     */
    private Boolean allowmagic;

    /**
     * Database Column Remarks:
     *   允许查看趋势统计
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowstat
     *
     * @mbg.generated
     */
    private Boolean allowstat;

    /**
     * Database Column Remarks:
     *   允许查看统计数据报表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowstatdata
     *
     * @mbg.generated
     */
    private Boolean allowstatdata;

    /**
     * Database Column Remarks:
     *   视频认证限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.videophotoignore
     *
     * @mbg.generated
     */
    private Boolean videophotoignore;

    /**
     * Database Column Remarks:
     *   允许查看视频认证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowviewvideophoto
     *
     * @mbg.generated
     */
    private Boolean allowviewvideophoto;

    /**
     * Database Column Remarks:
     *   允许使用应用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowmyop
     *
     * @mbg.generated
     */
    private Boolean allowmyop;

    /**
     * Database Column Remarks:
     *   购买道具折扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.magicdiscount
     *
     * @mbg.generated
     */
    private Boolean magicdiscount;

    /**
     * Database Column Remarks:
     *   二级域名最短长度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.domainlength
     *
     * @mbg.generated
     */
    private Short domainlength;

    /**
     * Database Column Remarks:
     *   发布操作需填验证码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.seccode
     *
     * @mbg.generated
     */
    private Boolean seccode;

    /**
     * Database Column Remarks:
     *   发表是否受防灌水限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.disablepostctrl
     *
     * @mbg.generated
     */
    private Boolean disablepostctrl;

    /**
     * Database Column Remarks:
     *   是否允许建立群组，0为不允许
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowbuildgroup
     *
     * @mbg.generated
     */
    private Boolean allowbuildgroup;

    /**
     * Database Column Remarks:
     *   是否允许直接在群组中发帖
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowgroupdirectpost
     *
     * @mbg.generated
     */
    private Boolean allowgroupdirectpost;

    /**
     * Database Column Remarks:
     *   是否允许在群组中发站外URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowgroupposturl
     *
     * @mbg.generated
     */
    private Boolean allowgroupposturl;

    /**
     * Database Column Remarks:
     *   编辑帖子时间限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.edittimelimit
     *
     * @mbg.generated
     */
    private Short edittimelimit;

    /**
     * Database Column Remarks:
     *   允许发布文章
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostarticle
     *
     * @mbg.generated
     */
    private Boolean allowpostarticle;

    /**
     * Database Column Remarks:
     *   允许下载本地图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowdownlocalimg
     *
     * @mbg.generated
     */
    private Boolean allowdownlocalimg;

    /**
     * Database Column Remarks:
     *   允许下载远程图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowdownremoteimg
     *
     * @mbg.generated
     */
    private Boolean allowdownremoteimg;

    /**
     * Database Column Remarks:
     *   发布文章是否需要审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowpostarticlemod
     *
     * @mbg.generated
     */
    private Boolean allowpostarticlemod;

    /**
     * Database Column Remarks:
     *   允许自定义模块使用HTML
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowspacediyhtml
     *
     * @mbg.generated
     */
    private Boolean allowspacediyhtml;

    /**
     * Database Column Remarks:
     *   允许自定义模块使用BBCODE
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowspacediybbcode
     *
     * @mbg.generated
     */
    private Boolean allowspacediybbcode;

    /**
     * Database Column Remarks:
     *   允许自定义模块使用[img]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowspacediyimgcode
     *
     * @mbg.generated
     */
    private Boolean allowspacediyimgcode;

    /**
     * Database Column Remarks:
     *   允许帖子点评 0:禁止 1:楼主 2:回复 3:All
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcommentpost
     *
     * @mbg.generated
     */
    private Boolean allowcommentpost;

    /**
     * Database Column Remarks:
     *   允许发表点评观点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcommentitem
     *
     * @mbg.generated
     */
    private Boolean allowcommentitem;

    /**
     * Database Column Remarks:
     *   允许发表回复点评
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcommentreply
     *
     * @mbg.generated
     */
    private Boolean allowcommentreply;

    /**
     * Database Column Remarks:
     *   允许设置回帖奖励
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowreplycredit
     *
     * @mbg.generated
     */
    private Boolean allowreplycredit;

    /**
     * Database Column Remarks:
     *   是否忽略要审核的关键字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.ignorecensor
     *
     * @mbg.generated
     */
    private Boolean ignorecensor;

    /**
     * Database Column Remarks:
     *   是否不受“只接收好友短消息”设置的限制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsendallpm
     *
     * @mbg.generated
     */
    private Boolean allowsendallpm;

    /**
     * Database Column Remarks:
     *   24小时内允许发短消息的数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsendpmmaxnum
     *
     * @mbg.generated
     */
    private Short allowsendpmmaxnum;

    /**
     * Database Column Remarks:
     *   相册中允许最大图片大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.maximagesize
     *
     * @mbg.generated
     */
    private Integer maximagesize;

    /**
     * Database Column Remarks:
     *   允许使用多媒体代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowmediacode
     *
     * @mbg.generated
     */
    private Boolean allowmediacode;

    /**
     * Database Column Remarks:
     *   允许使用开头动画代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowbegincode
     *
     * @mbg.generated
     */
    private Boolean allowbegincode;

    /**
     * Database Column Remarks:
     *   允许@用户 0：禁止 n:发帖时@的数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowat
     *
     * @mbg.generated
     */
    private Short allowat;

    /**
     * Database Column Remarks:
     *   允许定时发布主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowsetpublishdate
     *
     * @mbg.generated
     */
    private Boolean allowsetpublishdate;

    /**
     * Database Column Remarks:
     *   允许关注淘专辑数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowfollowcollection
     *
     * @mbg.generated
     */
    private Boolean allowfollowcollection;

    /**
     * Database Column Remarks:
     *   允许评论淘专辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcommentcollection
     *
     * @mbg.generated
     */
    private Boolean allowcommentcollection;

    /**
     * Database Column Remarks:
     *   允许创建淘专辑数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowcreatecollection
     *
     * @mbg.generated
     */
    private Short allowcreatecollection;

    /**
     * Database Column Remarks:
     *   强制设置安全提问才能进入后台管理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.forcesecques
     *
     * @mbg.generated
     */
    private Boolean forcesecques;

    /**
     * Database Column Remarks:
     *   强制登录方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.forcelogin
     *
     * @mbg.generated
     */
    private Boolean forcelogin;

    /**
     * Database Column Remarks:
     *   是否展示广告
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.closead
     *
     * @mbg.generated
     */
    private Boolean closead;

    /**
     * Database Column Remarks:
     *   创建群组需要消耗的积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.buildgroupcredits
     *
     * @mbg.generated
     */
    private Short buildgroupcredits;

    /**
     * Database Column Remarks:
     *   允许主题内容生成图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup_field.allowimgcontent
     *
     * @mbg.generated
     */
    private Boolean allowimgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_usergroup_field
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Short key) {
        this.groupid = key;
    }

    @Override
    public Short valueOfKey() {
        return groupid;
    }
}