package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_usergroup
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonUsergroup extends BaseModelObject<Short> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.groupid
     *
     * @mbg.generated
     */
    private Short groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.radminid
     *
     * @mbg.generated
     */
    private Byte radminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.system
     *
     * @mbg.generated
     */
    private String system;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.grouptitle
     *
     * @mbg.generated
     */
    private String grouptitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.creditshigher
     *
     * @mbg.generated
     */
    private Integer creditshigher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.creditslower
     *
     * @mbg.generated
     */
    private Integer creditslower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.stars
     *
     * @mbg.generated
     */
    private Byte stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowvisit
     *
     * @mbg.generated
     */
    private Boolean allowvisit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowsendpm
     *
     * @mbg.generated
     */
    private Boolean allowsendpm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowinvite
     *
     * @mbg.generated
     */
    private Boolean allowinvite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowmailinvite
     *
     * @mbg.generated
     */
    private Boolean allowmailinvite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.maxinvitenum
     *
     * @mbg.generated
     */
    private Byte maxinvitenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.inviteprice
     *
     * @mbg.generated
     */
    private Short inviteprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.maxinviteday
     *
     * @mbg.generated
     */
    private Short maxinviteday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_usergroup
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Short key) {
        this.groupid = key;
    }

    @Override
    public Short valueOfKey() {
        return groupid;
    }
}