package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_nav
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonNav extends BaseModelObject<Short> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.parentid
     *
     * @mbg.generated
     */
    private Short parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.identifier
     *
     * @mbg.generated
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.target
     *
     * @mbg.generated
     */
    private Boolean target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.available
     *
     * @mbg.generated
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.displayorder
     *
     * @mbg.generated
     */
    private Byte displayorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.highlight
     *
     * @mbg.generated
     */
    private Boolean highlight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.level
     *
     * @mbg.generated
     */
    private Boolean level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.subtype
     *
     * @mbg.generated
     */
    private Boolean subtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.subcols
     *
     * @mbg.generated
     */
    private Boolean subcols;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.subname
     *
     * @mbg.generated
     */
    private String subname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.suburl
     *
     * @mbg.generated
     */
    private String suburl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.navtype
     *
     * @mbg.generated
     */
    private Boolean navtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_nav.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_nav
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Short key) {
        this.id = key;
    }

    @Override
    public Short valueOfKey() {
        return id;
    }
}