package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_admincp_cmenu
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonAdmincpCmenu extends BaseModelObject<Short> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.sort
     *
     * @mbg.generated
     */
    private Boolean sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.displayorder
     *
     * @mbg.generated
     */
    private Byte displayorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.clicks
     *
     * @mbg.generated
     */
    private Short clicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_cmenu.dateline
     *
     * @mbg.generated
     */
    private Integer dateline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_admincp_cmenu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Short key) {
        this.id = key;
    }

    @Override
    public Short valueOfKey() {
        return id;
    }
}