package com.xstudio.discuzx.ultrax.model;

import java.io.Serializable;

import com.xstudio.core.BaseModelObject;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Database Table Remarks:
 *   后台管理组
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_admincp_group
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonAdmincpGroup extends BaseModelObject<Short> implements Serializable {
    /**
     * Database Column Remarks:
     *   后台组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_group.cpgroupid
     *
     * @mbg.generated
     */
    private Short cpgroupid;

    /**
     * Database Column Remarks:
     *   后台组名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_admincp_group.cpgroupname
     *
     * @mbg.generated
     */
    private String cpgroupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_admincp_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Short key) {
        this.cpgroupid = key;
    }

    @Override
    public Short valueOfKey() {
        return cpgroupid;
    }
}