package com.xstudio.discuzx.ultrax.model;

import com.xstudio.tool.utils.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Database Table Remarks:
 *   设置表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_setting
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonSetting extends BaseModelObject<String> implements Serializable {
    /**
     * Database Column Remarks:
     *   变量名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_setting.skey
     *
     * @mbg.generated
     */
    private String skey;

    /**
     * Database Column Remarks:
     *   值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_setting.svalue
     *
     * @mbg.generated
     */
    private String svalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_setting
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(String key) {
        this.skey = key;
    }

    @Override
    public String valueOfKey() {
        return skey;
    }
}