package com.xstudio.discuzx.ultrax.model;

import java.io.Serializable;

import com.alibaba.fastjson.annotation.JSONField;
import com.xstudio.core.BaseModelObject;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Database Table Remarks:
 *   用户主表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_member
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonMember extends BaseModelObject<Long> implements Serializable {
    /**
     * Database Column Remarks:
     *   会员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.password
     *
     * @mbg.generated
     */
    @JSONField(serialize = false)
    private String password;

    /**
     * Database Column Remarks:
     *   判断用户是否已经删除 需要discuz程序加判断，并增加整体清理的功能。原home字段为flag
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   email是否经过验证 home字段为emailcheck
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.emailstatus
     *
     * @mbg.generated
     */
    private Boolean emailstatus;

    /**
     * Database Column Remarks:
     *   是否有头像 home字段为avatar
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.avatarstatus
     *
     * @mbg.generated
     */
    private Boolean avatarstatus;

    /**
     * Database Column Remarks:
     *   视频认证状态 home
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.videophotostatus
     *
     * @mbg.generated
     */
    private Boolean videophotostatus;

    /**
     * Database Column Remarks:
     *   管理员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.adminid
     *
     * @mbg.generated
     */
    private Boolean adminid;

    /**
     * Database Column Remarks:
     *   会员组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.groupid
     *
     * @mbg.generated
     */
    private Short groupid;

    /**
     * Database Column Remarks:
     *   用户组有效期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.groupexpiry
     *
     * @mbg.generated
     */
    private Integer groupexpiry;

    /**
     * Database Column Remarks:
     *   扩展用户组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.extgroupids
     *
     * @mbg.generated
     */
    private String extgroupids;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.regdate
     *
     * @mbg.generated
     */
    private Integer regdate;

    /**
     * Database Column Remarks:
     *   总积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.credits
     *
     * @mbg.generated
     */
    private Integer credits;

    /**
     * Database Column Remarks:
     *   短信声音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.notifysound
     *
     * @mbg.generated
     */
    private Boolean notifysound;

    /**
     * Database Column Remarks:
     *   时区校正
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.timeoffset
     *
     * @mbg.generated
     */
    private String timeoffset;

    /**
     * Database Column Remarks:
     *   新短消息数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.newpm
     *
     * @mbg.generated
     */
    private Short newpm;

    /**
     * Database Column Remarks:
     *   新提醒数目
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.newprompt
     *
     * @mbg.generated
     */
    private Short newprompt;

    /**
     * Database Column Remarks:
     *   标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.accessmasks
     *
     * @mbg.generated
     */
    private Boolean accessmasks;

    /**
     * Database Column Remarks:
     *   标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.allowadmincp
     *
     * @mbg.generated
     */
    private Boolean allowadmincp;

    /**
     * Database Column Remarks:
     *   是否只接收好友短消息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.onlyacceptfriendpm
     *
     * @mbg.generated
     */
    private Boolean onlyacceptfriendpm;

    /**
     * Database Column Remarks:
     *   用户是否绑定QC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.conisbind
     *
     * @mbg.generated
     */
    private Boolean conisbind;

    /**
     * Database Column Remarks:
     *   是否冻结
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.freeze
     *
     * @mbg.generated
     */
    private Boolean freeze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Long key) {
        this.uid = key;
    }

    @Override
    public Long valueOfKey() {
        return uid;
    }
}