package com.xstudio.discuzx.ultrax.model;

import com.xstudio.tool.utils.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Database Table Remarks:
 *   用户组表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_usergroup
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonUsergroup extends BaseModelObject<Short> implements Serializable {
    /**
     * Database Column Remarks:
     *   会员组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.groupid
     *
     * @mbg.generated
     */
    private Short groupid;

    /**
     * Database Column Remarks:
     *   关联关管理组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.radminid
     *
     * @mbg.generated
     */
    private Byte radminid;

    /**
     * Database Column Remarks:
     *   类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   会员是否可以自由进出
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.system
     *
     * @mbg.generated
     */
    private String system;

    /**
     * Database Column Remarks:
     *   组头衔
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.grouptitle
     *
     * @mbg.generated
     */
    private String grouptitle;

    /**
     * Database Column Remarks:
     *   该组的积分上限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.creditshigher
     *
     * @mbg.generated
     */
    private Integer creditshigher;

    /**
     * Database Column Remarks:
     *   该组的积分下限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.creditslower
     *
     * @mbg.generated
     */
    private Integer creditslower;

    /**
     * Database Column Remarks:
     *   星星数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.stars
     *
     * @mbg.generated
     */
    private Byte stars;

    /**
     * Database Column Remarks:
     *   组头衔颜色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   允许访问
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowvisit
     *
     * @mbg.generated
     */
    private Boolean allowvisit;

    /**
     * Database Column Remarks:
     *   是否允许发送短信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowsendpm
     *
     * @mbg.generated
     */
    private Boolean allowsendpm;

    /**
     * Database Column Remarks:
     *   允许使用邀请注册
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowinvite
     *
     * @mbg.generated
     */
    private Boolean allowinvite;

    /**
     * Database Column Remarks:
     *   允许通过论坛邮件系统发送邀请码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.allowmailinvite
     *
     * @mbg.generated
     */
    private Boolean allowmailinvite;

    /**
     * Database Column Remarks:
     *   最大邀请码拥有数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.maxinvitenum
     *
     * @mbg.generated
     */
    private Byte maxinvitenum;

    /**
     * Database Column Remarks:
     *   邀请码购买价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.inviteprice
     *
     * @mbg.generated
     */
    private Short inviteprice;

    /**
     * Database Column Remarks:
     *   邀请码有效期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_usergroup.maxinviteday
     *
     * @mbg.generated
     */
    private Short maxinviteday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_usergroup
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Short key) {
        this.groupid = key;
    }

    @Override
    public Short valueOfKey() {
        return groupid;
    }
}