package com.xstudio.discuzx.ultrax.model;

import java.io.Serializable;

import com.xstudio.core.BaseModelObject;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Database Table Remarks:
 *   地区表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_district
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CommonDistrict extends BaseModelObject<Integer> implements Serializable {
    /**
     * Database Column Remarks:
     *   地区ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_district.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   地区名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_district.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   地区等级：1，省级；2，市级；3，县级；4，乡镇
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_district.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     * Database Column Remarks:
     *   使用对象：0:都不启用; 1:出生地; 2:居住地; 3:都启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_district.usetype
     *
     * @mbg.generated
     */
    private Boolean usetype;

    /**
     * Database Column Remarks:
     *   上级地区ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_district.upid
     *
     * @mbg.generated
     */
    private Integer upid;

    /**
     * Database Column Remarks:
     *   显示顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_district.displayorder
     *
     * @mbg.generated
     */
    private Short displayorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_district
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Integer key) {
        this.id = key;
    }

    @Override
    public Integer valueOfKey() {
        return id;
    }
}