package com.xstudio.discuzx.ultrax.model;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_forum_moderator
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ForumModerator extends ForumModeratorKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_moderator.displayorder
     *
     * @mbg.generated
     */
    private Byte displayorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_moderator.inherited
     *
     * @mbg.generated
     */
    private Boolean inherited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_forum_moderator
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}