package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_forum_forum
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ForumForum extends BaseModelObject<Integer> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.fup
     *
     * @mbg.generated
     */
    private Integer fup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.displayorder
     *
     * @mbg.generated
     */
    private Short displayorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.styleid
     *
     * @mbg.generated
     */
    private Short styleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.threads
     *
     * @mbg.generated
     */
    private Integer threads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.posts
     *
     * @mbg.generated
     */
    private Integer posts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.todayposts
     *
     * @mbg.generated
     */
    private Integer todayposts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.yesterdayposts
     *
     * @mbg.generated
     */
    private Integer yesterdayposts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.rank
     *
     * @mbg.generated
     */
    private Short rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.oldrank
     *
     * @mbg.generated
     */
    private Short oldrank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.lastpost
     *
     * @mbg.generated
     */
    private String lastpost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowsmilies
     *
     * @mbg.generated
     */
    private Boolean allowsmilies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowhtml
     *
     * @mbg.generated
     */
    private Boolean allowhtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowbbcode
     *
     * @mbg.generated
     */
    private Boolean allowbbcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowimgcode
     *
     * @mbg.generated
     */
    private Boolean allowimgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowmediacode
     *
     * @mbg.generated
     */
    private Boolean allowmediacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowanonymous
     *
     * @mbg.generated
     */
    private Boolean allowanonymous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowpostspecial
     *
     * @mbg.generated
     */
    private Short allowpostspecial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowspecialonly
     *
     * @mbg.generated
     */
    private Boolean allowspecialonly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowappend
     *
     * @mbg.generated
     */
    private Boolean allowappend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.alloweditrules
     *
     * @mbg.generated
     */
    private Boolean alloweditrules;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowfeed
     *
     * @mbg.generated
     */
    private Boolean allowfeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowside
     *
     * @mbg.generated
     */
    private Boolean allowside;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.recyclebin
     *
     * @mbg.generated
     */
    private Boolean recyclebin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.modnewposts
     *
     * @mbg.generated
     */
    private Boolean modnewposts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.jammer
     *
     * @mbg.generated
     */
    private Boolean jammer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.disablewatermark
     *
     * @mbg.generated
     */
    private Boolean disablewatermark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.inheritedmod
     *
     * @mbg.generated
     */
    private Boolean inheritedmod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.autoclose
     *
     * @mbg.generated
     */
    private Short autoclose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.forumcolumns
     *
     * @mbg.generated
     */
    private Byte forumcolumns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.catforumcolumns
     *
     * @mbg.generated
     */
    private Byte catforumcolumns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.threadcaches
     *
     * @mbg.generated
     */
    private Boolean threadcaches;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.alloweditpost
     *
     * @mbg.generated
     */
    private Boolean alloweditpost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.simple
     *
     * @mbg.generated
     */
    private Boolean simple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.modworks
     *
     * @mbg.generated
     */
    private Boolean modworks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.allowglobalstick
     *
     * @mbg.generated
     */
    private Boolean allowglobalstick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.level
     *
     * @mbg.generated
     */
    private Short level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.commoncredits
     *
     * @mbg.generated
     */
    private Integer commoncredits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.archive
     *
     * @mbg.generated
     */
    private Boolean archive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.recommend
     *
     * @mbg.generated
     */
    private Short recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.favtimes
     *
     * @mbg.generated
     */
    private Integer favtimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.sharetimes
     *
     * @mbg.generated
     */
    private Integer sharetimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.disablethumb
     *
     * @mbg.generated
     */
    private Boolean disablethumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forum.disablecollect
     *
     * @mbg.generated
     */
    private Boolean disablecollect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_forum_forum
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Integer key) {
        this.fid = key;
    }

    @Override
    public Integer valueOfKey() {
        return fid;
    }
}