package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_forum_forumfield
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ForumForumfield extends BaseModelObject<Integer> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.redirect
     *
     * @mbg.generated
     */
    private String redirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.attachextensions
     *
     * @mbg.generated
     */
    private String attachextensions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.jointype
     *
     * @mbg.generated
     */
    private Boolean jointype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.gviewperm
     *
     * @mbg.generated
     */
    private Boolean gviewperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.membernum
     *
     * @mbg.generated
     */
    private Short membernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.dateline
     *
     * @mbg.generated
     */
    private Integer dateline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.lastupdate
     *
     * @mbg.generated
     */
    private Integer lastupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.activity
     *
     * @mbg.generated
     */
    private Integer activity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.founderuid
     *
     * @mbg.generated
     */
    private Integer founderuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.foundername
     *
     * @mbg.generated
     */
    private String foundername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.banner
     *
     * @mbg.generated
     */
    private String banner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.groupnum
     *
     * @mbg.generated
     */
    private Short groupnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.picstyle
     *
     * @mbg.generated
     */
    private Boolean picstyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.widthauto
     *
     * @mbg.generated
     */
    private Boolean widthauto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.noantitheft
     *
     * @mbg.generated
     */
    private Boolean noantitheft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.noforumhidewater
     *
     * @mbg.generated
     */
    private Boolean noforumhidewater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.noforumrecommend
     *
     * @mbg.generated
     */
    private Boolean noforumrecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.livetid
     *
     * @mbg.generated
     */
    private Integer livetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.description
     *
     * @mbg.generated
     */
    public String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.creditspolicy
     *
     * @mbg.generated
     */
    public String creditspolicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.formulaperm
     *
     * @mbg.generated
     */
    public String formulaperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.moderators
     *
     * @mbg.generated
     */
    public String moderators;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.rules
     *
     * @mbg.generated
     */
    public String rules;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.threadtypes
     *
     * @mbg.generated
     */
    public String threadtypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.threadsorts
     *
     * @mbg.generated
     */
    public String threadsorts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.viewperm
     *
     * @mbg.generated
     */
    public String viewperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.postperm
     *
     * @mbg.generated
     */
    public String postperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.replyperm
     *
     * @mbg.generated
     */
    public String replyperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.getattachperm
     *
     * @mbg.generated
     */
    public String getattachperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.postattachperm
     *
     * @mbg.generated
     */
    public String postattachperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.postimageperm
     *
     * @mbg.generated
     */
    public String postimageperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.spviewperm
     *
     * @mbg.generated
     */
    public String spviewperm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.seotitle
     *
     * @mbg.generated
     */
    public String seotitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.keywords
     *
     * @mbg.generated
     */
    public String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.seodescription
     *
     * @mbg.generated
     */
    public String seodescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.supe_pushsetting
     *
     * @mbg.generated
     */
    public String supePushsetting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.modrecommend
     *
     * @mbg.generated
     */
    public String modrecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.threadplugin
     *
     * @mbg.generated
     */
    public String threadplugin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.replybg
     *
     * @mbg.generated
     */
    public String replybg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.extra
     *
     * @mbg.generated
     */
    public String extra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.commentitem
     *
     * @mbg.generated
     */
    public String commentitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_forumfield.relatedgroup
     *
     * @mbg.generated
     */
    public String relatedgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_forum_forumfield
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Integer key) {
        this.fid = key;
    }

    @Override
    public Integer valueOfKey() {
        return fid;
    }
}