package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_forum_threadclass
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ForumThreadclass extends BaseModelObject<Integer> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_threadclass.typeid
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_threadclass.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_threadclass.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_threadclass.displayorder
     *
     * @mbg.generated
     */
    private Integer displayorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_threadclass.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_threadclass.moderators
     *
     * @mbg.generated
     */
    private Boolean moderators;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_forum_threadclass
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Integer key) {
        this.typeid = key;
    }

    @Override
    public Integer valueOfKey() {
        return typeid;
    }
}