package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_forum_moderator
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ForumModeratorKey extends BaseModelObject<ForumModeratorKey> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_moderator.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_forum_moderator.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_forum_moderator
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(ForumModeratorKey key) {
        this.uid = key.getUid();
        this.fid = key.getFid();
    }

    @Override
    public ForumModeratorKey valueOfKey() {
        ForumModeratorKey key = new ForumModeratorKey();
        key.setUid(this.uid);
        key.setFid(this.fid);
        return key;
    }
}