package com.xstudio.discuzx.ultrax.model;

import com.xstudio.core.BaseModelObject;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_ucenter_members
 */
public class UcenterMembers extends BaseModelObject<Integer> implements Serializable {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   登录密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   E-mail
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   漫游ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.myid
     *
     * @mbg.generated
     */
    private String myid;

    /**
     * Database Column Remarks:
     *   漫游ID KEY
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.myidkey
     *
     * @mbg.generated
     */
    private String myidkey;

    /**
     * Database Column Remarks:
     *   注册IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.regip
     *
     * @mbg.generated
     */
    private String regip;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.regdate
     *
     * @mbg.generated
     */
    private Integer regdate;

    /**
     * Database Column Remarks:
     *   最后登录IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.lastloginip
     *
     * @mbg.generated
     */
    private Integer lastloginip;

    /**
     * Database Column Remarks:
     *   最后登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.lastlogintime
     *
     * @mbg.generated
     */
    private Integer lastlogintime;

    /**
     * Database Column Remarks:
     *   密码哈希
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * Database Column Remarks:
     *   密码哈希
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.secques
     *
     * @mbg.generated
     */
    private String secques;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Integer key) {
        this.uid = key;
    }

    @Override
    public Integer valueOfKey() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.uid
     *
     * @return the value of pre_ucenter_members.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.uid
     *
     * @param uid the value for pre_ucenter_members.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.username
     *
     * @return the value of pre_ucenter_members.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.username
     *
     * @param username the value for pre_ucenter_members.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.password
     *
     * @return the value of pre_ucenter_members.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.password
     *
     * @param password the value for pre_ucenter_members.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.email
     *
     * @return the value of pre_ucenter_members.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.email
     *
     * @param email the value for pre_ucenter_members.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.myid
     *
     * @return the value of pre_ucenter_members.myid
     *
     * @mbg.generated
     */
    public String getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.myid
     *
     * @param myid the value for pre_ucenter_members.myid
     *
     * @mbg.generated
     */
    public void setMyid(String myid) {
        this.myid = myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.myidkey
     *
     * @return the value of pre_ucenter_members.myidkey
     *
     * @mbg.generated
     */
    public String getMyidkey() {
        return myidkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.myidkey
     *
     * @param myidkey the value for pre_ucenter_members.myidkey
     *
     * @mbg.generated
     */
    public void setMyidkey(String myidkey) {
        this.myidkey = myidkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.regip
     *
     * @return the value of pre_ucenter_members.regip
     *
     * @mbg.generated
     */
    public String getRegip() {
        return regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.regip
     *
     * @param regip the value for pre_ucenter_members.regip
     *
     * @mbg.generated
     */
    public void setRegip(String regip) {
        this.regip = regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.regdate
     *
     * @return the value of pre_ucenter_members.regdate
     *
     * @mbg.generated
     */
    public Integer getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.regdate
     *
     * @param regdate the value for pre_ucenter_members.regdate
     *
     * @mbg.generated
     */
    public void setRegdate(Integer regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.lastloginip
     *
     * @return the value of pre_ucenter_members.lastloginip
     *
     * @mbg.generated
     */
    public Integer getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.lastloginip
     *
     * @param lastloginip the value for pre_ucenter_members.lastloginip
     *
     * @mbg.generated
     */
    public void setLastloginip(Integer lastloginip) {
        this.lastloginip = lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.lastlogintime
     *
     * @return the value of pre_ucenter_members.lastlogintime
     *
     * @mbg.generated
     */
    public Integer getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.lastlogintime
     *
     * @param lastlogintime the value for pre_ucenter_members.lastlogintime
     *
     * @mbg.generated
     */
    public void setLastlogintime(Integer lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.salt
     *
     * @return the value of pre_ucenter_members.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.salt
     *
     * @param salt the value for pre_ucenter_members.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_ucenter_members.secques
     *
     * @return the value of pre_ucenter_members.secques
     *
     * @mbg.generated
     */
    public String getSecques() {
        return secques;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_ucenter_members.secques
     *
     * @param secques the value for pre_ucenter_members.secques
     *
     * @mbg.generated
     */
    public void setSecques(String secques) {
        this.secques = secques;
    }
}