package com.xstudio.discuzx.ultrax.model;

import com.xstudio.tool.utils.BaseModelObject;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_ucenter_members
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class UcenterMembers extends BaseModelObject<Long> implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.myid
     *
     * @mbg.generated
     */
    private String myid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.myidkey
     *
     * @mbg.generated
     */
    private String myidkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.regip
     *
     * @mbg.generated
     */
    private String regip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.regdate
     *
     * @mbg.generated
     */
    private Integer regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.lastloginip
     *
     * @mbg.generated
     */
    private Integer lastloginip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.lastlogintime
     *
     * @mbg.generated
     */
    private Integer lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.secques
     *
     * @mbg.generated
     */
    private String secques;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void assignKeyValue(Long key) {
        this.uid = key;
    }

    @Override
    public Long valueOfKey() {
        return uid;
    }
}