package com.xstudio.discuzx.model;

import com.xstudio.common.service.BaseModelObject;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_member_status
 */
@Data
public class CommonMemberStatus extends BaseModelObject implements Serializable {
    /**
     * Database Column Remarks:
     *   会员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * Database Column Remarks:
     *   注册IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.regip
     *
     * @mbg.generated
     */
    private String regip;

    /**
     * Database Column Remarks:
     *   最后登录IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.lastip
     *
     * @mbg.generated
     */
    private String lastip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.port
     *
     * @mbg.generated
     */
    private Short port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastvisitBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastvisitEnd;

    /**
     * Database Column Remarks:
     *   最后访问
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.lastvisit
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastvisit;

    /**
     * Database Column Remarks:
     *   最后活动
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.lastactivity
     *
     * @mbg.generated
     */
    private Integer lastactivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastpostBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastpostEnd;

    /**
     * Database Column Remarks:
     *   最后发表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.lastpost
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastpost;

    /**
     * Database Column Remarks:
     *   上次发送email时间 home原字段为lastsend
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.lastsendmail
     *
     * @mbg.generated
     */
    private Integer lastsendmail;

    /**
     * Database Column Remarks:
     *   是否隐身登录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.invisible
     *
     * @mbg.generated
     */
    private Boolean invisible;

    /**
     * Database Column Remarks:
     *   买家信用等级及积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.buyercredit
     *
     * @mbg.generated
     */
    private Short buyercredit;

    /**
     * Database Column Remarks:
     *   卖家信用等级及积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.sellercredit
     *
     * @mbg.generated
     */
    private Short sellercredit;

    /**
     * Database Column Remarks:
     *   个人空间收藏次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.favtimes
     *
     * @mbg.generated
     */
    private Integer favtimes;

    /**
     * Database Column Remarks:
     *   个人空间分享次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.sharetimes
     *
     * @mbg.generated
     */
    private Integer sharetimes;

    /**
     * Database Column Remarks:
     *   个人资料完成度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_status.profileprogress
     *
     * @mbg.generated
     */
    private Byte profileprogress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Object key) {
        if (null == key ||  "null".equals(key)) {
            setUid(null);
            return;
        }
        setUid(Long.valueOf(String.valueOf(key)));
    }

    @Override
    public String getKey() {
        return String.valueOf(getUid());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public Date getLastvisitBegin() {
        return lastvisitBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public Date getLastvisitEnd() {
        return lastvisitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public void setLastvisitBegin(Date lastvisitBegin) {
        this.lastvisitBegin = lastvisitBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public void setLastvisitEnd(Date lastvisitEnd) {
        this.lastvisitEnd = lastvisitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public Date getLastpostBegin() {
        return lastpostBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public Date getLastpostEnd() {
        return lastpostEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public void setLastpostBegin(Date lastpostBegin) {
        this.lastpostBegin = lastpostBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member_status
     *
     * @mbg.generated
     */
    public void setLastpostEnd(Date lastpostEnd) {
        this.lastpostEnd = lastpostEnd;
    }
}