package com.xstudio.discuzx.model;

import com.xstudio.common.service.BaseModelObject;
import java.io.Serializable;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_member_count
 */
@Data
public class CommonMemberCount extends BaseModelObject implements Serializable {
    /**
     * Database Column Remarks:
     *   会员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * Database Column Remarks:
     *   声望
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits1
     *
     * @mbg.generated
     */
    private Integer extcredits1;

    /**
     * Database Column Remarks:
     *   金钱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits2
     *
     * @mbg.generated
     */
    private Integer extcredits2;

    /**
     * Database Column Remarks:
     *   扩展
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits3
     *
     * @mbg.generated
     */
    private Integer extcredits3;

    /**
     * Database Column Remarks:
     *   扩展
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits4
     *
     * @mbg.generated
     */
    private Integer extcredits4;

    /**
     * Database Column Remarks:
     *   扩展
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits5
     *
     * @mbg.generated
     */
    private Integer extcredits5;

    /**
     * Database Column Remarks:
     *   扩展
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits6
     *
     * @mbg.generated
     */
    private Integer extcredits6;

    /**
     * Database Column Remarks:
     *   扩展
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits7
     *
     * @mbg.generated
     */
    private Integer extcredits7;

    /**
     * Database Column Remarks:
     *   扩展
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.extcredits8
     *
     * @mbg.generated
     */
    private Integer extcredits8;

    /**
     * Database Column Remarks:
     *   好友个数 home
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.friends
     *
     * @mbg.generated
     */
    private Short friends;

    /**
     * Database Column Remarks:
     *   帖子数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.posts
     *
     * @mbg.generated
     */
    private Integer posts;

    /**
     * Database Column Remarks:
     *   主题数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.threads
     *
     * @mbg.generated
     */
    private Integer threads;

    /**
     * Database Column Remarks:
     *   精华数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.digestposts
     *
     * @mbg.generated
     */
    private Short digestposts;

    /**
     * Database Column Remarks:
     *   记录数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.doings
     *
     * @mbg.generated
     */
    private Short doings;

    /**
     * Database Column Remarks:
     *   日志数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.blogs
     *
     * @mbg.generated
     */
    private Short blogs;

    /**
     * Database Column Remarks:
     *   相册数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.albums
     *
     * @mbg.generated
     */
    private Short albums;

    /**
     * Database Column Remarks:
     *   分享数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.sharings
     *
     * @mbg.generated
     */
    private Short sharings;

    /**
     * Database Column Remarks:
     *   上传附件占用的空间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.attachsize
     *
     * @mbg.generated
     */
    private Integer attachsize;

    /**
     * Database Column Remarks:
     *   空间查看数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.views
     *
     * @mbg.generated
     */
    private Integer views;

    /**
     * Database Column Remarks:
     *   在线时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.oltime
     *
     * @mbg.generated
     */
    private Short oltime;

    /**
     * Database Column Remarks:
     *   当天上传附件数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.todayattachs
     *
     * @mbg.generated
     */
    private Short todayattachs;

    /**
     * Database Column Remarks:
     *   当天上传附件容量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.todayattachsize
     *
     * @mbg.generated
     */
    private Integer todayattachsize;

    /**
     * Database Column Remarks:
     *   广播数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.feeds
     *
     * @mbg.generated
     */
    private Integer feeds;

    /**
     * Database Column Remarks:
     *   听众数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.follower
     *
     * @mbg.generated
     */
    private Integer follower;

    /**
     * Database Column Remarks:
     *   收听数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.following
     *
     * @mbg.generated
     */
    private Integer following;

    /**
     * Database Column Remarks:
     *   新增听众数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.newfollower
     *
     * @mbg.generated
     */
    private Integer newfollower;

    /**
     * Database Column Remarks:
     *   黑名单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_count.blacklist
     *
     * @mbg.generated
     */
    private Integer blacklist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member_count
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Object key) {
        if (null == key ||  "null".equals(key)) {
            setUid(null);
            return;
        }
        setUid(Long.valueOf(String.valueOf(key)));
    }

    @Override
    public String getKey() {
        return String.valueOf(getUid());
    }
}