package com.xstudio.discuzx.model;

import com.xstudio.common.service.BaseModelObject;
import java.io.Serializable;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_member_newprompt
 */
@Data
public class CommonMemberNewprompt extends BaseModelObject implements Serializable {
    /**
     * Database Column Remarks:
     *   会员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_newprompt.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member_newprompt.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member_newprompt
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Object key) {
        if (null == key ||  "null".equals(key)) {
            setUid(null);
            return;
        }
        setUid(Long.valueOf(String.valueOf(key)));
    }

    @Override
    public String getKey() {
        return String.valueOf(getUid());
    }
}