package com.xstudio.discuzx.model;

import com.xstudio.common.service.BaseModelObject;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_common_credit_rule_log
 */
@Data
public class CommonCreditRuleLog extends BaseModelObject implements Serializable {
    /**
     * Database Column Remarks:
     *   策略日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.clid
     *
     * @mbg.generated
     */
    private Long clid;

    /**
     * Database Column Remarks:
     *   策略日志所有者uID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * Database Column Remarks:
     *   策略ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.rid
     *
     * @mbg.generated
     */
    private Long rid;

    /**
     * Database Column Remarks:
     *   版块ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.fid
     *
     * @mbg.generated
     */
    private Long fid;

    /**
     * Database Column Remarks:
     *   策略被执行总次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     * Database Column Remarks:
     *   周期被执行次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.cyclenum
     *
     * @mbg.generated
     */
    private Integer cyclenum;

    /**
     * Database Column Remarks:
     *   扩展1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits1
     *
     * @mbg.generated
     */
    private Integer extcredits1;

    /**
     * Database Column Remarks:
     *   扩展2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits2
     *
     * @mbg.generated
     */
    private Integer extcredits2;

    /**
     * Database Column Remarks:
     *   扩展3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits3
     *
     * @mbg.generated
     */
    private Integer extcredits3;

    /**
     * Database Column Remarks:
     *   扩展4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits4
     *
     * @mbg.generated
     */
    private Integer extcredits4;

    /**
     * Database Column Remarks:
     *   扩展5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits5
     *
     * @mbg.generated
     */
    private Integer extcredits5;

    /**
     * Database Column Remarks:
     *   扩展6
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits6
     *
     * @mbg.generated
     */
    private Integer extcredits6;

    /**
     * Database Column Remarks:
     *   扩展7
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits7
     *
     * @mbg.generated
     */
    private Integer extcredits7;

    /**
     * Database Column Remarks:
     *   扩展8
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.extcredits8
     *
     * @mbg.generated
     */
    private Integer extcredits8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date starttimeBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date starttimeEnd;

    /**
     * Database Column Remarks:
     *   周期开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.starttime
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date datelineBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date datelineEnd;

    /**
     * Database Column Remarks:
     *   策略最后执行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_credit_rule_log.dateline
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date dateline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Object key) {
        if (null == key ||  "null".equals(key)) {
            setClid(null);
            return;
        }
        setClid(Long.valueOf(String.valueOf(key)));
    }

    @Override
    public String getKey() {
        return String.valueOf(getClid());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public Date getStarttimeBegin() {
        return starttimeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public Date getStarttimeEnd() {
        return starttimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public void setStarttimeBegin(Date starttimeBegin) {
        this.starttimeBegin = starttimeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public void setStarttimeEnd(Date starttimeEnd) {
        this.starttimeEnd = starttimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public Date getDatelineBegin() {
        return datelineBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public Date getDatelineEnd() {
        return datelineEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public void setDatelineBegin(Date datelineBegin) {
        this.datelineBegin = datelineBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_credit_rule_log
     *
     * @mbg.generated
     */
    public void setDatelineEnd(Date datelineEnd) {
        this.datelineEnd = datelineEnd;
    }
}