package com.xstudio.discuzx.model;

import com.xstudio.common.service.BaseModelObject;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_ucenter_members
 */
@Data
public class UcenterMembers extends BaseModelObject implements Serializable {
    /**
     * Database Column Remarks:
     *   会员UID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.myid
     *
     * @mbg.generated
     */
    private String myid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.myidkey
     *
     * @mbg.generated
     */
    private String myidkey;

    /**
     * Database Column Remarks:
     *   注册IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.regip
     *
     * @mbg.generated
     */
    private String regip;

    /**
     * Database Column Remarks:
     *   最后登录IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.lastloginip
     *
     * @mbg.generated
     */
    private Integer lastloginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastlogintimeBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastlogintimeEnd;

    /**
     * Database Column Remarks:
     *   最后登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.lastlogintime
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastlogintime;

    /**
     * Database Column Remarks:
     *   盐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * Database Column Remarks:
     *   安全提示问题(独立加密)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_members.secques
     *
     * @mbg.generated
     */
    private String secques;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Object key) {
        if (null == key ||  "null".equals(key)) {
            setUid(null);
            return;
        }
        setUid(Long.valueOf(String.valueOf(key)));
    }

    @Override
    public String getKey() {
        return String.valueOf(getUid());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    public Date getLastlogintimeBegin() {
        return lastlogintimeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    public Date getLastlogintimeEnd() {
        return lastlogintimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    public void setLastlogintimeBegin(Date lastlogintimeBegin) {
        this.lastlogintimeBegin = lastlogintimeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_ucenter_members
     *
     * @mbg.generated
     */
    public void setLastlogintimeEnd(Date lastlogintimeEnd) {
        this.lastlogintimeEnd = lastlogintimeEnd;
    }
}