package com.xstudio.discuzx.model;

import com.xstudio.common.service.BaseModelObject;
import java.io.Serializable;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_ucenter_failedlogins
 */
@Data
public class UcenterFailedlogins extends BaseModelObject implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_failedlogins.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_failedlogins.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   失败次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_ucenter_failedlogins.count
     *
     * @mbg.generated
     */
    private Boolean count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_ucenter_failedlogins
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Object key) {
        if (null == key ||  "null".equals(key)) {
            setId(null);
            return;
        }
        setId(Long.valueOf(String.valueOf(key)));
    }

    @Override
    public String getKey() {
        return String.valueOf(getId());
    }
}